### ISSUE TITLE
JwtOpenSSL.d Error

### ISSUE THREAD

**Issue by kkangert** [huntlabs/hunt-jwt#1]
C:\Users\kangert\AppData\Local\dub\packages\hunt-jwt-0.2.0-beta.2\hunt-jwt\source\hunt\jwt\JwtOpenSSL.d(180,36): Error: function `deimos.openssl.ecdsa.d2i_ECDSA_SIG(ECDSA_SIG_st** sig, const(ubyte)** pp, int len)` is not callable using argument types `(typeof(null), const(ubyte)**, long)`

C:\Users\kangert\AppData\Local\dub\packages\hunt-jwt-0.2.0-beta.2\hunt-jwt\source\hunt\jwt\JwtOpenSSL.d(180,36):        cannot pass argument `cast(long)slen` of type `long` to parameter `int len`

Windows10下

**Comment by Heromyth** [comment]
Fixed in commit https://github.com/huntlabs/hunt-jwt/commit/0c3ab5d8cd771140ddcd5c506a35e1fa1e8196d9.
